### ISSUE TITLE
"gistContent.find is not a function"

### ISSUE THREAD

**Issue by 1aozhang** [not-ivy/melon#1]
Hi

I deployed this project on deno deploy with required ENV set, and corresponding gist (links.json) created, but I get the following response:

"gistContent.find is not a function"

Any idea?

**Comment by kibibites** [comment]
can you go to the network tab in devtools and check the data returned for the gist fetch request?

**Comment by kibibites** [comment]
sorry; i forgot the request is made on the server :p

in that case, please make sure that the gist id and github token is provided correctly. the github token is classic instead of fine grained, and it should have the gist scope checked

**Comment by 1aozhang** [comment]
Hi

I figured it out by looking into the code and turns out 
the gist assigned should be named as links.json and should be an empty json array []

now it works fine.

Thanks and regards.
